
# Loads default set of integrations. Do not remove.
default_config:

# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
#  logs:
#    custom_components.saleryd_hrv: debug
#    pysaleryd: debug
