set_fireplace_mode:
  name: Set fireplace mode
  description: Set fireplace mode on or off
  fields:
    value:
      description: desired mode (0=Off,1=On)
      example: "1"
      required: true
      selector:
        number:
          min: 0
          max: 1
          mode: slider
set_cooling_mode:
  name: Set cooling mode
  description: Set cooling mode on or off
  fields:
    value:
      description: desired mode (0=Off,1=On)
      example: "1"
      required: true
      selector:
        number:
          min: 0
          max: 1
          mode: slider
set_ventilation_mode:
  name: Set ventilation mode
  description: Set ventilation mode
  fields:
    value:
      description: desired mode (0=Home,1=Away,2=Boost)
      example: "1"
      required: true
      selector:
        number:
          min: 0
          max: 2
          mode: slider
set_temperature_mode:
  name: Set temperature mode
  description: Set temperature mode
  fields:
    value:
      description: desired mode (0=Normal,1=Economy,2=Cool)
      example: "1"
      required: true
      selector:
        number:
          min: 0
          max: 2
          mode: slider
