set_fireplace_mode:
  name: Set fireplace mode
  description: Set fireplace mode on or off
  fields:
    value:
      name: Value
      description: desired mode (0=Off,1=On)
      example: "1"
      required: true
      selector:
        number:
          min: 0
          max: 1
          mode: slider
set_cooling_mode:
  name: Set cooling mode
  description: Set cooling mode on or off
  fields:
    value:
      name: Value
      description: desired mode (0=Off,1=On)
      example: "1"
      required: true
      selector:
        number:
          min: 0
          max: 1
          mode: slider
set_ventilation_mode:
  name: Set ventilation mode
  description: Set ventilation mode
  fields:
    value:
      name: Value
      description: desired mode (0=Home,1=Away,2=Boost)
      example: "1"
      required: true
      selector:
        number:
          min: 0
          max: 2
          mode: slider
set_temperature_mode:
  name: Set temperature mode
  description: Set temperature mode
  fields:
    value:
      name: Value
      description: desired mode (0=Normal,1=Economy,2=Cool)
      example: "1"
      required: true
      selector:
        number:
          min: 0
          max: 2
          mode: slider
set_system_active_mode:
  name: Set system active mode
  description: Set system active mode
  fields:
    value:
      name: Value
      description: desired mode (0=Off,1=On,2=Reset)
      example: "1"
      required: true
      selector:
        number:
          min: 0
          max: 2
          mode: slider
unlock_maintenance_settings:
  name: Unlock maintenance settings
  description: Unlock maintenance settings
  fields:
    value:
      name: Value
      description: Maintenance password
      example: "6666"
      required: true
      selector:
        text:
          type: password
set_target_temperature_normal:
  name: Set normal target temperature
  description: Set target temperature for normal temperature mode
  fields:
    value:
      name: Value
      description: target temperature
      example: "18"
      required: true
      selector:
        number:
          min: 10
          max: 30
          mode: slider
set_target_temperature_cool:
  name: Set cool target temperature
  description: Set target temperature for cool temperature mode
  fields:
    value:
      name: Value
      description: target temperature
      example: "18"
      required: true
      selector:
        number:
          min: 10
          max: 30
          mode: slider
set_target_temperature_economy:
  name: Set economy target temperature
  description: Set target temperature for economy temperature mode
  fields:
    value:
      name: Value
      description: target temperature
      example: "18"
      required: true
      selector:
        number:
          min: 10
          max: 30
          mode: slider
