set_fireplace_mode:
  description: Set fireplace mode on or off
  fields:
    value:
      description: desired value (0=Off,1=On)
      example: "1"
      required: true
      selector:
        number:
          min: 0
          max: 1
          mode: slider
set_cooling_mode:
  description: Set cooling mode on or off
  fields:
    value:
      description: desired value (0=Off,1=On)
      example: "1"
      required: true
      selector:
        number:
          min: 0
          max: 1
          mode: slider
set_ventilation_mode:
  description: Set ventilation mode
  fields:
    value:
      description: desired value (0=Home,1=Away,2=High)
      example: "1"
      required: true
      selector:
        number:
          min: 0
          max: 2
          mode: slider
set_temperature_mode:
  description: Set temperature mode
  fields:
    value:
      description: desired value (0=Cooling,1=Economy,2=Normal)
      example: "1"
      required: true
      selector:
        number:
          min: 0
          max: 2
          mode: slider

