#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/../../"

# Create config dir if not present
if [[ ! -d "${PWD}/.devcontainer/config" ]]; then
    mkdir -p "${PWD}/.devcontainer/config"
    hass --config "${PWD}/.devcontainer/config" --script ensure_config
fi

# Set the path to custom_components
## This let's us have the structure we want <root>/custom_components/saleryd_hrv
## while at the same time have Home Assistant configuration inside <root>/.devcontainer/config
## without resulting to symlinks.
export PYTHONPATH="${PYTHONPATH}:${PWD}/custom_components"

DEBUG_ARGS=""

if [[ ! -z "$DEBUG" ]]; then
  # debug with debugpy
  DEBUG_ARGS="-Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678"
  if [[ ! -z "$DEBUG_WAIT" ]]; then
    # wait for debugger connection
    DEBUG_ARGS="$DEBUG_ARGS --wait-for-client"
  fi
fi

# Start Home Assistant
echo "$DEBUG_ARGS" -m homeassistant --config "${PWD}/.devcontainer/config"

python3 $DEBUG_ARGS -m homeassistant --config "${PWD}/.devcontainer/config" && echo "Waiting for debugger.."
