#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/../../"

# Create config dir if not present
if [[ ! -d "${PWD}/.devcontainer/config" ]]; then
    mkdir -p "${PWD}/.devcontainer/config"
    hass --config "${PWD}/.devcontainer/config" --script ensure_config
fi

# Set the path to custom_components
## This let's us have the structure we want <root>/custom_components/saleryd_hrv
## while at the same time have Home Assistant configuration inside <root>/.devcontainer/config
## without resulting to symlinks.
export PYTHONPATH="${PYTHONPATH}:${PWD}/custom_components"

HASS_ARGS="-m homeassistant --config ${PWD}/.devcontainer/config"
DEBUG_ARGS="-Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678"

if [[ ! -z "$DEBUG" ]]; then
  # debug with debugpy
  python $DEBUG_ARGS $HASS_ARGS
elif [[ ! -z "$DEBUG_WAIT" ]]; then
    # wait for debugger connection
    echo "Waiting for debugger to connect.."
    python $DEBUG_ARGS --wait-for-client $HASS_ARGS
else
  # Run Home Assistant
  python $HASS_ARGS
fi
