name: Create release

on:
  workflow_dispatch:
    inputs:
      pre_release:
        type: boolean
        description: "pre-release?"
        required: true
jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: Changelog action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v4
        with:
          github-token: ${{ secrets.github_token }}
          output-file: "false"
          preset: conventionalcommits
          version-file: "custom_components/saleryd_hrv/manifest.json"
          pre-release: ${{ inputs.pre_release }}
          skip-ci: false

      - name: Create Release
        uses: ncipollo/release-action@v1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        with:
          token: ${{ secrets.github_token }}
          commit: ${{ github.sha }}
          tag: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          name: ${{ steps.changelog.outputs.tag }}
          prerelease: ${{ inputs.pre_release }}
